# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14LDpO1-QiOWhtzK26KjS3P6ZggO1Tqv-
"""

pip install -q chronos-forecasting shap lightgbm transformers torch

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import lightgbm as lgb
import shap
import torch
from sklearn.metrics import mean_absolute_error, root_mean_squared_error
from chronos import ChronosPipeline

print("✅ Environment successfully configured with GPU status:", torch.cuda.is_available())

import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_absolute_error, root_mean_squared_error

# Configure crisp corporate styling for executive-ready charts
plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
sns.set_palette("muted")

print("✅ Advanced layer modules initialized successfully.")

class SmartGridMetaLearner:
    """
    Blends Tabular Machine Learning (LightGBM) with Time-Series LLMs
    (Chronos) using an optimized Ridge Meta-Learner model.
    """
    def __init__(self):
        # Constrain to positive alpha weights to prevent inverse tracking anomalies
        self.meta_model = Ridge(alpha=1.0, positive=True, fit_intercept=False)

    def train_meta_learner(self, calibration_df, target_col):
        """
        Learns the operational strengths of both models from validation data.
        """
        print("🔗 Training Stacking Meta-Learner on base model residual vectors...")
        # Extract individual model prediction fields
        X_calib = calibration_df[['lgb_pred', 'chronos_pred']].values
        y_calib = calibration_df[target_col].values

        self.meta_model.fit(X_calib, y_calib)

        # Save learned weight coefficients
        self.lgb_weight = self.meta_model.coef_[0]
        self.chronos_weight = self.meta_model.coef_[1]

        print(f"📊 Learned Blending Architecture Weights -> LightGBM: {self.lgb_weight:.3f} | Chronos: {self.chronos_weight:.3f}")

    def predict_hybrid(self, inference_df):
        """Generates the optimal stacked prediction vector."""
        X_inf = inference_df[['lgb_pred', 'chronos_pred']].values
        return self.meta_model.predict(X_inf)

import os
print(os.getcwd())

print(os.listdir())

import glob
print(glob.glob('**/energy_dataset.csv', recursive=True))
print(glob.glob('**/weather_features.csv', recursive=True))

import pandas as pd
df_energy = pd.read_csv("energy_dataset.csv")
df_weather = pd.read_csv("weather_features.csv")
print(df_energy.columns.tolist())
print(df_weather.columns.tolist())

target_col = 'total load actual'

import pandas as pd

df_energy = pd.read_csv("energy_dataset.csv")
df_weather = pd.read_csv("weather_features.csv")

df_energy['time'] = pd.to_datetime(df_energy['time'], utc=True)
df_weather['dt_iso'] = pd.to_datetime(df_weather['dt_iso'], utc=True)

df_weather_clean = df_weather.groupby('dt_iso').agg({
    'temp': 'mean', 'humidity': 'mean', 'wind_speed': 'mean'
}).reset_index()

df = pd.merge(df_energy, df_weather_clean, left_on='time', right_on='dt_iso', how='inner')
print(df.columns.tolist())  # sanity check
df = df.set_index('time').sort_index()

import pandas as pd
import numpy as np
import logging
from pathlib import Path
from typing import Optional

# --- Logging setup (cleaner than scattered print statements) ---
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("energy_pipeline")


def load_csv_safely(path: str, required_cols: Optional[list] = None) -> pd.DataFrame:
    """Load a CSV with existence, emptiness, and schema validation."""
    file_path = Path(path)
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    df = pd.read_csv(file_path)

    if df.empty:
        raise ValueError(f"{path} loaded but contains no rows.")

    if required_cols:
        missing = set(required_cols) - set(df.columns)
        if missing:
            raise KeyError(f"{path} is missing expected columns: {missing}")

    logger.info(f"Loaded {path} → shape={df.shape}")
    return df


def parse_datetime_column(df: pd.DataFrame, col: str, utc: bool = True) -> pd.DataFrame:
    """Convert a column to datetime, coercing bad values to NaT and reporting them."""
    before_na = df[col].isna().sum()
    df[col] = pd.to_datetime(df[col], utc=utc, errors="coerce")
    after_na = df[col].isna().sum()

    dropped = after_na - before_na
    if dropped > 0:
        logger.warning(f"{dropped} unparseable timestamps in '{col}' converted to NaT.")

    return df


def optimize_dtypes(df: pd.DataFrame) -> pd.DataFrame:
    """Downcast numeric columns to save memory — useful for large weather/energy datasets."""
    float_cols = df.select_dtypes(include=["float64"]).columns
    int_cols = df.select_dtypes(include=["int64"]).columns

    df[float_cols] = df[float_cols].apply(pd.to_numeric, downcast="float")
    df[int_cols] = df[int_cols].apply(pd.to_numeric, downcast="integer")

    return df


def build_weather_aggregate(
    df_weather: pd.DataFrame,
    dt_col: str = "dt_iso",
    agg_map: Optional[dict] = None,
) -> pd.DataFrame:
    """
    Aggregate multi-city weather data into a single national signal per timestamp.
    Defaults to mean, but agg_map lets you customize per-column logic
    (e.g. max wind_speed for grid-risk modeling instead of mean).
    """
    agg_map = agg_map or {"temp": "mean", "humidity": "mean", "wind_speed": "mean"}

    missing = set(agg_map.keys()) - set(df_weather.columns)
    if missing:
        raise KeyError(f"Weather aggregation columns missing from data: {missing}")

    df_agg = df_weather.groupby(dt_col).agg(agg_map).reset_index()
    logger.info(f"Aggregated weather data → {df_agg.shape[0]} unique timestamps.")
    return df_agg


def merge_energy_weather(
    df_energy: pd.DataFrame,
    df_weather_clean: pd.DataFrame,
    energy_time_col: str = "time",
    weather_time_col: str = "dt_iso",
) -> pd.DataFrame:
    """Merge energy and weather data with pre/post row-count diagnostics."""
    pre_rows = len(df_energy)

    df = pd.merge(
        df_energy,
        df_weather_clean,
        left_on=energy_time_col,
        right_on=weather_time_col,
        how="inner",
    )

    post_rows = len(df)
    dropped_pct = (1 - post_rows / pre_rows) * 100 if pre_rows else 0

    logger.info(f"Merged dataset shape: {df.shape}")
    if dropped_pct > 0:
        logger.warning(
            f"{dropped_pct:.2f}% of energy rows had no matching weather timestamp and were dropped."
        )

    return df



ENERGY_CSV = "energy_dataset.csv"
WEATHER_CSV = "weather_features.csv"

df_energy = load_csv_safely(ENERGY_CSV, required_cols=["time"])
df_weather = load_csv_safely(WEATHER_CSV, required_cols=["dt_iso", "temp", "humidity", "wind_speed"])

df_energy = parse_datetime_column(df_energy, "time")
df_weather = parse_datetime_column(df_weather, "dt_iso")

df_weather_clean = build_weather_aggregate(df_weather)

df = merge_energy_weather(df_energy, df_weather_clean)
print(df.columns.tolist())  # sanity check

df = df.set_index("time").sort_index()
df = optimize_dtypes(df)

logger.info(f"Final dataset ready → shape={df.shape}, memory={df.memory_usage(deep=True).sum() / 1e6:.2f} MB")

!pip install -q --upgrade torch chronos-forecasting lightgbm shap statsmodels

!pip uninstall -y torch torchvision torchaudio

!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

!pip install -q chronos-forecasting lightgbm shap statsmodels --no-deps
!pip install -q accelerate

import torch, torchvision
print("torch:", torch.__version__)
print("torchvision:", torchvision.__version__)
print("CUDA available:", torch.cuda.is_available())

import warnings
warnings.filterwarnings("ignore")

import logging
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import lightgbm as lgb
import shap
from statsmodels.tsa.seasonal import seasonal_decompose
from sklearn.metrics import mean_absolute_error, root_mean_squared_error

import torch
from chronos import BaseChronosPipeline

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("energy_pipeline")

def load_csv_safely(path: str, required_cols: Optional[list] = None) -> pd.DataFrame:
    """Load a CSV with existence, emptiness, and schema validation."""
    file_path = Path(path)
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    df = pd.read_csv(file_path)
    if df.empty:
        raise ValueError(f"{path} loaded but contains no rows.")

    if required_cols:
        missing = set(required_cols) - set(df.columns)
        if missing:
            raise KeyError(f"{path} is missing expected columns: {missing}")

    logger.info(f"Loaded {path} -> shape={df.shape}")
    return df


def detect_target_column(df: pd.DataFrame) -> str:
    """Auto-detect the real-world 'total load actual' column regardless of
    whether it uses spaces or underscores in the source file."""
    candidates = [
        c for c in df.columns
        if "total" in c.lower() and "load" in c.lower() and "actual" in c.lower()
    ]
    if not candidates:
        raise KeyError(
            f"Could not locate a 'total load actual' style column. "
            f"Available columns: {df.columns.tolist()}"
        )
    return candidates[0]

CITY_POPULATION_WEIGHTS = {
    "Madrid": 6_700_000,
    "Barcelona": 5_500_000,
    "Valencia": 1_650_000,
    "Seville": 1_300_000,
    "Bilbao": 1_000_000,
}


def build_population_weighted_weather(df_weather: pd.DataFrame) -> pd.DataFrame:
    """Collapse 5-city weather data into a single population-weighted
    national signal per timestamp, instead of a naive city-average."""
    df_weather = df_weather.copy()
    df_weather["city_name"] = df_weather["city_name"].str.strip()

    unknown_cities = set(df_weather["city_name"].unique()) - set(CITY_POPULATION_WEIGHTS)
    if unknown_cities:
        logger.warning(f"Unweighted / unknown cities found, dropping: {unknown_cities}")
        df_weather = df_weather[df_weather["city_name"].isin(CITY_POPULATION_WEIGHTS)]

    df_weather["weight"] = df_weather["city_name"].map(CITY_POPULATION_WEIGHTS)

    def weighted_avg(group: pd.DataFrame, col: str) -> float:
        return np.average(group[col], weights=group["weight"])

    records = []
    for dt, group in df_weather.groupby("dt_iso"):
        records.append({
            "dt_iso": dt,
            "temp": weighted_avg(group, "temp"),
            "humidity": weighted_avg(group, "humidity"),
            "wind_speed": weighted_avg(group, "wind_speed"),
        })
    df_agg = pd.DataFrame(records)
    logger.info(f"Population-weighted weather aggregated -> {df_agg.shape[0]} timestamps.")
    return df_agg

def add_fourier_terms(df: pd.DataFrame, period: int, order: int, prefix: str) -> pd.DataFrame:
    """Generic Fourier-term generator. `order` harmonics capture richer
    seasonal shape than a single sin/cos pair (e.g. double-peak daily
    industrial demand curves)."""
    t = np.arange(len(df))
    for k in range(1, order + 1):
        df[f"{prefix}_sin_{k}"] = np.sin(2 * np.pi * k * t / period)
        df[f"{prefix}_cos_{k}"] = np.cos(2 * np.pi * k * t / period)
    return df


def load_and_engineer_data(energy_path: str, weather_path: str):
    print("🧹 Parsing and aligning multi-city industrial data vectors...")

    df_energy = load_csv_safely(energy_path, required_cols=["time"])
    df_weather = load_csv_safely(
        weather_path, required_cols=["dt_iso", "city_name", "temp", "humidity", "wind_speed"]
    )

    # --- Time-zone alignment: Spain's TSO data is timezone-aware; normalize
    # everything to UTC to avoid silent misalignment across DST transitions ---
    df_energy["time"] = pd.to_datetime(df_energy["time"], utc=True)
    df_weather["dt_iso"] = pd.to_datetime(df_weather["dt_iso"], utc=True)

    df_weather_clean = build_population_weighted_weather(df_weather)

    df = pd.merge(df_energy, df_weather_clean, left_on="time", right_on="dt_iso", how="inner")
    dropped_pct = (1 - len(df) / len(df_energy)) * 100
    if dropped_pct > 0:
        logger.warning(f"{dropped_pct:.2f}% of energy rows dropped on weather merge.")

    df = df.set_index("time").sort_index()

    target_col = detect_target_column(df)
    print(f"✅ Detected target column: '{target_col}'")
    df[target_col] = df[target_col].ffill()

    # --- Keep the TSO's own official day-ahead forecast as a benchmark
    # column: this lets us later ask "did our model beat the grid operator's
    # own forecast?" instead of only benchmarking against a naive baseline ---
    if "total load forecast" in df.columns:
        df["tso_forecast_benchmark"] = df["total load forecast"]

    # Scale temperature metric to Celsius if required
    df["temp_c"] = df["temp"] - 273.15 if df["temp"].mean() > 200 else df["temp"]

    # Industrial Degree Days
    df["CDD"] = np.maximum(0, df["temp_c"] - 22.0)
    df["HDD"] = np.maximum(0, 18.0 - df["temp_c"])

    # Calendar-cyclic signals (kept for LightGBM interpretability via SHAP)
    df["hour"] = df.index.hour
    df["day_of_week"] = df.index.dayofweek
    df["month"] = df.index.month
    df["hour_sin"] = np.sin(2 * np.pi * df["hour"] / 24.0)
    df["hour_cos"] = np.cos(2 * np.pi * df["hour"] / 24.0)
    df["day_sin"] = np.sin(2 * np.pi * df["day_of_week"] / 7.0)
    df["day_cos"] = np.cos(2 * np.pi * df["day_of_week"] / 7.0)

    # Higher-order Fourier terms for annual seasonality (captures summer AC
    # peaks + winter heating peaks better than a single sinusoid)
    df = add_fourier_terms(df, period=365.25 * 24, order=3, prefix="annual")

    # Structural autoregressive lags
    df["load_lag_24"] = df[target_col].shift(24)
    df["load_lag_168"] = df[target_col].shift(168)
    df["load_rolling_mean_24"] = df[target_col].shift(1).rolling(window=24).mean()
    df["load_rolling_std_24"] = df[target_col].shift(1).rolling(window=24).std()

    return df.dropna(), target_col

ENERGY_CSV = "energy_dataset.csv"
WEATHER_CSV = "weather_features.csv"

processed_df, target = load_and_engineer_data(ENERGY_CSV, WEATHER_CSV)
print(f"Final engineered shape: {processed_df.shape}")
processed_df.head()

def load_and_engineer_data(energy_path, weather_path):
    print("🧹 Parsing and aligning multi-city industrial data vectors...")

    df_energy = load_csv_safely(energy_path, required_cols=["time"])
    df_weather = load_csv_safely(
        weather_path, required_cols=["dt_iso", "city_name", "temp", "humidity", "wind_speed"]
    )

    df_energy["time"] = pd.to_datetime(df_energy["time"], utc=True)
    df_weather["dt_iso"] = pd.to_datetime(df_weather["dt_iso"], utc=True)

    df_weather_clean = build_population_weighted_weather(df_weather)

    df = pd.merge(df_energy, df_weather_clean, left_on="time", right_on="dt_iso", how="inner")
    df = df.set_index("time").sort_index()

    target_col = detect_target_column(df)
    print(f"✅ Detected target column: '{target_col}'")
    df[target_col] = df[target_col].ffill()

    if "total load forecast" in df.columns:
        df["tso_forecast_benchmark"] = df["total load forecast"]

    df["temp_c"] = df["temp"] - 273.15 if df["temp"].mean() > 200 else df["temp"]
    df["CDD"] = np.maximum(0, df["temp_c"] - 22.0)
    df["HDD"] = np.maximum(0, 18.0 - df["temp_c"])

    df["hour"] = df.index.hour
    df["day_of_week"] = df.index.dayofweek
    df["month"] = df.index.month
    df["hour_sin"] = np.sin(2 * np.pi * df["hour"] / 24.0)
    df["hour_cos"] = np.cos(2 * np.pi * df["hour"] / 24.0)
    df["day_sin"] = np.sin(2 * np.pi * df["day_of_week"] / 7.0)
    df["day_cos"] = np.cos(2 * np.pi * df["day_of_week"] / 7.0)

    df = add_fourier_terms(df, period=365.25 * 24, order=3, prefix="annual")

    df["load_lag_24"] = df[target_col].shift(24)
    df["load_lag_168"] = df[target_col].shift(168)
    df["load_rolling_mean_24"] = df[target_col].shift(1).rolling(window=24).mean()
    df["load_rolling_std_24"] = df[target_col].shift(1).rolling(window=24).std()

    # ---- THE FIX: only require non-null values in columns this pipeline
    # actually needs, instead of df.dropna() which wipes every row because
    # some unused raw columns (e.g. 'generation hydro pumped storage
    # aggregated') are 100% NaN across the whole dataset ----
    required_cols = [
        target_col, "temp_c", "CDD", "HDD",
        "hour_sin", "hour_cos", "day_sin", "day_cos",
        "load_lag_24", "load_lag_168", "load_rolling_mean_24", "load_rolling_std_24",
    ] + [c for c in df.columns if c.startswith("annual_")]

    if "tso_forecast_benchmark" in df.columns:
        required_cols.append("tso_forecast_benchmark")

    df_clean = df.dropna(subset=required_cols)
    return df_clean, target_col

ENERGY_CSV = "energy_dataset.csv"
WEATHER_CSV = "weather_features.csv"

processed_df, target = load_and_engineer_data(ENERGY_CSV, WEATHER_CSV)
print(f"Final shape: {processed_df.shape}")
assert len(processed_df) > 0, "Pipeline produced an empty dataframe — check for all-NaN columns."
processed_df.head()

decomposition = seasonal_decompose(processed_df[target], model="additive", period=24)
fig = decomposition.plot()
fig.set_size_inches(10, 8)
plt.tight_layout()
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose

decomposition = seasonal_decompose(processed_df[target], model="additive", period=24)
fig = decomposition.plot()
fig.set_size_inches(10, 8)
plt.tight_layout()
plt.show()

forecast_horizon = 24

fourier_cols = [c for c in processed_df.columns if c.startswith("annual_")]
features = [
    "temp_c", "humidity", "wind_speed", "CDD", "HDD",
    "hour_sin", "hour_cos", "day_sin", "day_cos",
    "load_lag_24", "load_lag_168", "load_rolling_mean_24", "load_rolling_std_24",
] + fourier_cols

missing_feats = [f for f in features if f not in processed_df.columns]
if missing_feats:
    raise KeyError(f"Missing expected feature columns: {missing_feats}")

train_df = processed_df.iloc[:-forecast_horizon]
test_df = processed_df.iloc[-forecast_horizon:].copy()

model = lgb.LGBMRegressor(
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=31,
    random_state=42,
    verbosity=-1,
)
model.fit(train_df[features], train_df[target])
test_df["lgb_pred"] = model.predict(test_df[features])

lgb_mae = mean_absolute_error(test_df[target], test_df["lgb_pred"])
lgb_rmse = root_mean_squared_error(test_df[target], test_df["lgb_pred"])
print(f"LightGBM  -> MAE: {lgb_mae:,.1f} MW | RMSE: {lgb_rmse:,.1f} MW")

if "tso_forecast_benchmark" in test_df.columns:
    tso_mae = mean_absolute_error(test_df[target], test_df["tso_forecast_benchmark"])
    tso_rmse = root_mean_squared_error(test_df[target], test_df["tso_forecast_benchmark"])
    print(f"TSO Forecast -> MAE: {tso_mae:,.1f} MW | RMSE: {tso_rmse:,.1f} MW")

print("\n📊 Calculating model transparency matrix using SHAP...")
explainer = shap.TreeExplainer(model)
sample_size = min(2000, len(processed_df))
shap_sample = processed_df[features].sample(sample_size, random_state=42)
shap_values = explainer(shap_sample)

plt.figure(figsize=(10, 5))
shap.summary_plot(shap_values, shap_sample, show=False)
plt.title("SHAP Feature Attribution: Drivers of Smart-Grid Energy Fluctuations", fontsize=12)
plt.tight_layout()
plt.show()

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"⚙️  Loading Chronos-Bolt foundation model on device: {device}")

chronos_pipeline = BaseChronosPipeline.from_pretrained(
    "amazon/chronos-bolt-base",
    device_map=device,
    torch_dtype=torch.bfloat16 if device == "cuda" else torch.float32,
)

context_series = torch.tensor(train_df[target].values, dtype=torch.float32)

quantiles, mean_forecast = chronos_pipeline.predict_quantiles(
    inputs=context_series,
    prediction_length=forecast_horizon,
    quantile_levels=[0.1, 0.5, 0.9],
)

test_df["chronos_pred"] = mean_forecast[0].numpy()
test_df["chronos_lower_10"] = quantiles[0, :, 0].numpy()
test_df["chronos_upper_90"] = quantiles[0, :, 2].numpy()

chronos_mae = mean_absolute_error(test_df[target], test_df["chronos_pred"])
chronos_rmse = root_mean_squared_error(test_df[target], test_df["chronos_pred"])
print(f"Chronos (zero-shot) -> MAE: {chronos_mae:,.1f} MW | RMSE: {chronos_rmse:,.1f} MW")

def execute_advanced_layer(test_df, target_col):
    print("🚀 Injecting Advanced Hybrid Orchestration Layer...")

    # Instantiate our blending orchestrator class
    orchestrator = SmartGridMetaLearner()

    # Split the evaluation window in half to prevent data leakage
    midpoint = len(test_df) // 2
    calibration_slice = test_df.iloc[:midpoint].copy()
    evaluation_slice = test_df.iloc[midpoint:].copy()

    # Fallback safety guard if data rows are minimal
    if len(calibration_slice) == 0 or len(evaluation_slice) == 0:
        calibration_slice = test_df.copy()
        evaluation_slice = test_df.copy()

    # Fit the meta-regressor weights over the calibration split
    orchestrator.train_meta_learner(calibration_slice, target_col)

    # Compute the final advanced combined forecast array
    evaluation_slice['hybrid_ensemble_pred'] = orchestrator.predict_hybrid(evaluation_slice)

    return evaluation_slice, orchestrator

# Execute the partition split
advanced_eval_df, trained_orchestrator = execute_advanced_layer(test_df, target)

actuals = advanced_eval_df[target]
lgb_mae = mean_absolute_error(actuals, advanced_eval_df['lgb_pred'])
chronos_mae = mean_absolute_error(actuals, advanced_eval_df['chronos_pred'])
hybrid_mae = mean_absolute_error(actuals, advanced_eval_df['hybrid_ensemble_pred'])
hybrid_rmse = root_mean_squared_error(actuals, advanced_eval_df['hybrid_ensemble_pred'])

print("🏆 ADVANCED SCOREBOARD PERFORMANCE REPORT")
print("==================================================")
print(f"• Baseline LightGBM MAE         : {lgb_mae:.2f} MW")
print(f"• Foundation Chronos-Bolt MAE   : {chronos_mae:.2f} MW")
print(f"--------------------------------------------------")
print(f"• 🌟 Hybrid Stacked Ensemble MAE: {hybrid_mae:.2f} MW")
print(f"• 🌟 Hybrid Stacked Ensemble RMSE: {hybrid_rmse:.2f} MW")
print(f"==================================================")
print(f"🔥 Optimization Delta: Saved {min(lgb_mae, chronos_mae) - hybrid_mae:.2f} MW in residual tracking error!")

plt.figure(figsize=(14, 6))
plt.plot(test_df.index, test_df[target], label="Actual Load", color="black", linewidth=2)
plt.plot(test_df.index, test_df["lgb_pred"], label="LightGBM (trained)", linestyle="--")
plt.plot(test_df.index, test_df["chronos_pred"], label="Chronos-Bolt (zero-shot)", linestyle="--")
if "tso_forecast_benchmark" in test_df.columns:
    plt.plot(test_df.index, test_df["tso_forecast_benchmark"], label="TSO Official Forecast", linestyle=":")
plt.fill_between(
    test_df.index, test_df["chronos_lower_10"], test_df["chronos_upper_90"],
    alpha=0.15, label="Chronos 10-90% interval"
)
plt.title(f"24h-Ahead Spain Electricity Load Forecast: Model Comparison")
plt.xlabel("Time")
plt.ylabel("Load (MW)")
plt.legend()
plt.tight_layout()
plt.show()

print("\n===== FINAL SCOREBOARD (lower is better) =====")
print(f"{'Model':<25}{'MAE (MW)':>12}{'RMSE (MW)':>12}")
print(f"{'LightGBM':<25}{lgb_mae:>12,.1f}{lgb_rmse:>12,.1f}")
print(f"{'Chronos-Bolt (0-shot)':<25}{chronos_mae:>12,.1f}{chronos_rmse:>12,.1f}")
if "tso_forecast_benchmark" in test_df.columns:
    print(f"{'TSO Official Forecast':<25}{tso_mae:>12,.1f}{tso_rmse:>12,.1f}")

plt.figure(figsize=(14, 6.5))

# Plot actual vs predictions
plt.plot(advanced_eval_df.index, actuals, label='Actual Spain Grid Load', color='#111111', linewidth=3.5, marker='o', markersize=6)
plt.plot(advanced_eval_df.index, advanced_eval_df['lgb_pred'], label='LightGBM (Tabular Tree Baseline)', color='#FF416C', linestyle=':', linewidth=2, alpha=0.8)
plt.plot(advanced_eval_df.index, advanced_eval_df['chronos_pred'], label='Chronos-Bolt (Foundation LLM Model)', color='#00B4DB', linestyle=':', linewidth=2, alpha=0.8)
plt.plot(advanced_eval_df.index, advanced_eval_df['hybrid_ensemble_pred'], label='Meta-Learner Hybrid Ensemble (Stacked)', color='#8E2DE2', linewidth=3.5, linestyle='-')

# Customizing plot visuals for presentable reports
plt.title("Spain Smart-Grid Advanced Telemetry: Meta-Learner Model Blending Profile", fontsize=14, fontweight='bold', pad=15)
plt.xlabel("Timeline Evaluation Window Vector (UTC)", fontsize=11)
plt.ylabel("Power Magnitudes (Megawatts - MW)", fontsize=11)
plt.grid(True, linestyle='--', alpha=0.3)
plt.legend(fontsize=10.5, facecolor='#FFFFFF', frameon=True, shadow=True, loc='upper left')

# Auto-format timestamps nicely on x-axis
plt.gcf().autofmt_xdate()
plt.tight_layout()

# Render graph inside cell output
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Compute absolute error residuals for each model pipeline layer
eval_res = advanced_eval_df.copy()
eval_res['LGBM Error'] = eval_res[target] - eval_res['lgb_pred']
eval_res['Chronos Error'] = eval_res[target] - eval_res['chronos_pred']
eval_res['Hybrid Ensemble Error'] = eval_res[target] - eval_res['hybrid_ensemble_pred']

# Melt the dataframe structure to make it ready for Seaborn plotting
melted_errors = eval_res.melt(
    value_vars=['LGBM Error', 'Chronos Error', 'Hybrid Ensemble Error'],
    var_name='Model Architecture', value_name='Prediction Error Residual (MW)'
)

# Initialize a crisp corporate multi-panel visualization structure
fig, axes = plt.subplots(1, 2, figsize=(18, 6.5), gridspec_kw={'width_ratios': [1, 1]})

# Panel A: Violin Distribution Plots (Visualizes error density spreads)
sns.violinplot(
    x='Model Architecture', y='Prediction Error Residual (MW)',
    data=melted_errors, ax=axes[0], palette=['#FF416C', '#00B4DB', '#8E2DE2'], inner="quartile"
)
axes[0].axhline(0, color='black', linestyle='--', alpha=0.6)
axes[0].set_title("Systemic Residual Density Variance (Closer to 0 is Better)", fontsize=13, fontweight='bold')
axes[0].set_xlabel("")

# Panel B: Cumulative Distribution Function / Error KDE Curves
sns.kdeplot(data=eval_res['LGBM Error'], ax=axes[1], color='#FF416C', label='LightGBM Baseline', linewidth=2.5)
sns.kdeplot(data=eval_res['Chronos Error'], ax=axes[1], color='#00B4DB', label='Chronos-Bolt Foundation', linewidth=2.5)
sns.kdeplot(data=eval_res['Hybrid Ensemble Error'], ax=axes[1], color='#8E2DE2', label='Meta-Learner Hybrid', linewidth=3)
axes[1].axvline(0, color='black', linestyle='--', alpha=0.6)
axes[1].set_title("Operational Error Convergence Spectrum", fontsize=13, fontweight='bold')
axes[1].set_xlabel("Error Distance Metric Magnitude (MW)")
axes[1].legend(fontsize=10.5, facecolor='#FFFFFF', shadow=True)

plt.suptitle("Corporate Telemetry Audit: Model Reliability & Residual Stability Profiles", fontsize=15, fontweight='bold', y=0.98)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Extract weights safely from your previously trained Meta-Learner instance
lgb_w = trained_orchestrator.lgb_weight[0] if hasattr(trained_orchestrator.lgb_weight, "__len__") else trained_orchestrator.lgb_weight
chronos_w = trained_orchestrator.chronos_weight[1] if hasattr(trained_orchestrator.chronos_weight, "__len__") else trained_orchestrator.chronos_weight

# Normalize weights to construct an explicit 100% allocation slice framework
total_w = lgb_w + chronos_w
labels = ['LightGBM Tabular Logic Weights', 'Chronos Temporal Syntax Weights']
allocations = [lgb_w / total_w * 100, chronos_w / total_w * 100]

# Generate a high-impact corporate Donut-Ring Matrix Chart
plt.figure(figsize=(7, 7))
wedges, texts, autotexts = plt.pie(
    allocations, labels=labels, autopct='%1.1f%%', startangle=140,
    colors=['#FF416C', '#00B4DB'], pctdistance=0.75,
    textprops=dict(fontsize=11, fontweight='bold'),
    wedgeprops=dict(width=0.3, edgecolor='white', linewidth=3)
)

# Clean styling touches for presentation clarity
for autotext in autotexts:
    autotext.set_color('white')
    autotext.set_fontsize(12)

plt.title("Meta-Learner Dynamic Task Allocations: Balancing Tabular vs LLM Models", fontsize=13, fontweight='bold', pad=20)
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# 1. Initialize the canvas structure with sub-sampled dataframe entries
sampled_df = processed_df.sample(min(3000, len(processed_df)), random_state=42)
g = sns.JointGrid(data=sampled_df, x="temp_c", y=target, space=0)

# 2. Render core point clouds (FIX: Pass data=g.data explicitly into the scatterplot arguments)
g.plot_joint(
    sns.scatterplot, data=sampled_df, palette="magma", hue="humidity",
    alpha=0.6, size="humidity", sizes=(10, 80), edgecolor="none"
)

# 3. Overlay marginal distribution histogram tracks
g.plot_marginals(sns.histplot, kde=True, color="#8E2DE2", bins=35, alpha=0.4)

# 4. Apply clean typography styling labels
g.set_axis_labels(
    "Population-Weighted Regional Temperature Vector (°C)",
    "Actual Spain Total Power Consumption (MW)",
    fontsize=11, fontweight='bold'
)
g.fig.suptitle("Smart-Grid Weather Sensitivity Map: Multi-Variable Interaction Profile", fontsize=14, fontweight='bold', y=1.02)

plt.show()

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from scipy.interpolate import griddata

# 1. Isolate sample data arrays to keep browser rendering lightweight and fast
sample_3d = processed_df.sample(min(2000, len(processed_df)), random_state=42)
x_data = sample_3d['temp_c'].values
y_data = sample_3d['load_lag_24'].values
z_data = sample_3d[target].values

# 2. Build a uniform mesh grid space for mathematical surface interpolation
x_mesh = np.linspace(x_data.min(), x_data.max(), 40)
y_mesh = np.linspace(y_data.min(), y_data.max(), 40)
X_grid, Y_grid = np.meshgrid(x_mesh, y_mesh)

# Interpolate the Z-load data over the coordinate mesh points
Z_grid = griddata((x_data, y_data), z_data, (X_grid, Y_grid), method='linear')

# 3. Assemble the 3D Interactive Canvas Engine
fig = go.Figure()

# Layer A: Add actual industrial data observations as a 3D Scatter cloud
fig.add_trace(go.Scatter3d(
    x=x_data, y=y_data, z=z_data,
    mode='markers',
    marker=dict(
        size=3.5,
        color=z_data,               # Color code points based on consumption magnitude
        colorscale='Magma',          # Rich corporate palette
        opacity=0.65,
        colorbar=dict(title=dict(text="Load Magnitude (MW)", font=dict(size=11)), thickness=15)
    ),
    name="Actual Grid Observations"
))

# Layer B: Overlay the non-linear trend surface topology sheet
fig.add_trace(go.Surface(
    x=x_mesh, y=y_mesh, z=Z_grid,
    colorscale='Viridis',
    opacity=0.45,
    showscale=False,
    name="Continuous Trend Surface"
))

# 4. Apply clean, executive-ready typography and structural styling
fig.update_layout(
    title=dict(
        text="3D Smart-Grid Operational Topology: Mapping Weather & Lag Interaction Spaces",
        font=dict(size=16, family="Arial", color="#111111"),
        y=0.95
    ),
    scene=dict(
        xaxis=dict(title='Temperature Vector (°C)', backgroundcolor="#F8F9FA", gridcolor="#E9ECEF"),
        yaxis=dict(title='Historical Lag (24h Load MW)', backgroundcolor="#F8F9FA", gridcolor="#E9ECEF"),
        zaxis=dict(title='Target Actual Load (MW)', backgroundcolor="#F8F9FA", gridcolor="#E9ECEF")
    ),
    margin=dict(l=0, r=0, b=40, t=60),
    width=950,
    height=750,
    legend=dict(x=0.02, y=0.98, bgcolor="rgba(255,255,255,0.8)")
)

# Render the interactive panel inline within your Colab output window
fig.show()

import plotly.graph_objects as go

# Ensure your index features are cleanly parsed as text strings for hover metrics
time_stamps = advanced_eval_df.index.strftime('%Y-%m-%d %H:%M')

fig = go.Figure()

# Trace 1: True Real-World Grid Vector Path
fig.add_trace(go.Scatter3d(
    x=advanced_eval_df['temp_c'],
    y=advanced_eval_df['load_lag_24'],
    z=advanced_eval_df[target],
    mode='lines+markers',
    line=dict(color='#111111', width=5),
    marker=dict(size=5, color='#111111'),
    text=time_stamps,
    hoverinfo='text+x+y+z',
    name='True TSO Grid Path'
))

# Trace 2: Hybrid Meta-Learner Stacked Ensemble Predictive Projection Path
fig.add_trace(go.Scatter3d(
    x=advanced_eval_df['temp_c'],
    y=advanced_eval_df['load_lag_24'],
    z=advanced_eval_df['hybrid_ensemble_pred'],
    mode='lines+markers',
    line=dict(color='#8E2DE2', width=4, dash='dash'),
    marker=dict(size=4, color='#8E2DE2', symbol='diamond'),
    text=time_stamps,
    hoverinfo='text+x+y+z',
    name='Meta-Learner Ensemble Path'
))

# Configure executive-ready scene aesthetics
fig.update_layout(
    title=dict(
        text="3D Phase Trajectory: System Evaluation Across Predictive Flight Coordinates",
        font=dict(size=16, family="Arial")
    ),
    scene=dict(
        xaxis=dict(title='Temperature (°C)'),
        yaxis=dict(title='Historical Lag Vector (MW)'),
        zaxis=dict(title='Grid Load Output (MW)')
    ),
    margin=dict(l=0, r=0, b=40, t=60),
    width=950,
    height=750
)

fig.show()

import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

print("📊 Advanced statistical diagnostic packages loaded successfully.")

# 1. Clean the variable strings to comply with statsmodels formula formatting constraints
stat_df = processed_df.copy()
stat_df = stat_df.rename(columns={target: 'target_load'})

# 2. Divide into historical training context and validation slices
forecast_horizon = 24
train_stat = stat_df.iloc[:-forecast_horizon]
test_stat = stat_df.iloc[-forecast_horizon:].copy()

# 3. Formulate the structural regression equation containing weather and autoregressive features
formula = "target_load ~ temp_c + CDD + HDD + hour_sin + hour_cos + load_lag_24"

print("📐 Fitting Multi-Quantile Time-Series Framework...")
# Fit Median Load Model (Quantile 0.50)
median_model = smf.quantreg(formula, data=train_stat).fit(q=0.50)
# Fit Extreme Peak Risk Model (Quantile 0.95)
peak_model = smf.quantreg(formula, data=train_stat).fit(q=0.95)

# 4. Generate out-of-sample statistical predictions
test_stat['stat_median_pred'] = median_model.predict(test_stat)
test_stat['stat_peak_pred'] = peak_model.predict(test_stat)

print("✅ Quantile estimation processing complete.")

# Extract parameters for the 95th Percentile Model to show impact during extreme spikes
summary_coefs = peak_model.summary2().tables[1]

# Format the dataframe for presentation inside executive slide notes
presentation_table = summary_coefs[['Coef.', 'Std.Err.', 't', 'P>|t|']].copy()
presentation_table.columns = ['Coefficient Weight', 'Standard Error', 't-Statistic', 'p-Value (Significance)']

print("📋 EXECUTIVE STATISTICAL ATTRIBUTION MATRIX (95th Percentile Extreme Peak Model)")
print("=================================================================================")
print(presentation_table.round(4).to_string())
print("=================================================================================")
print("💡 Interpretation Tracker: A p-Value < 0.05 proves the variable statistically drives grid load changes.")

# Calculate error residuals from the historical base model run
train_stat_pred = median_model.predict(train_stat)
residuals = train_stat['target_load'] - train_stat_pred

# Run a formal Breusch-Pagan test to evaluate residual variance stability
from statsmodels.stats.diagnostic import het_breuschpagan
exog_vars = sm.add_constant(train_stat[['temp_c', 'CDD', 'HDD', 'hour_sin', 'hour_cos', 'load_lag_24']])
lm_stat, lm_p, f_stat, f_p = het_breuschpagan(residuals, exog_vars)

print("🔍 FORMAL RESIDUAL TELEMETRY DIAGNOSTIC STATUS")
print(f"--------------------------------------------------")
print(f"• Breusch-Pagan LM p-Value: {lm_p:.4e}")
if lm_p < 0.05:
    print("⚠️ Status: Heteroskedasticity Detected. Grid volatility changes dynamically with weather intensity.")
else:
    print("✅ Status: Homoskedasticity Confirmed. Error distributions remain stable across parameters.")
print(f"--------------------------------------------------")

plt.figure(figsize=(15, 6.5))

# Plot actual vs statistical boundaries
plt.plot(test_stat.index, test_stat['target_load'], label='Actual Spain Grid Load', color='#111111', linewidth=3.5, marker='o')
plt.plot(test_stat.index, test_stat['stat_median_pred'], label='Statistical Median Expectation (Q: 0.50)', color='#00B4DB', linestyle='--', linewidth=2.5)
plt.plot(test_stat.index, test_stat['stat_peak_pred'], label='Upper Operational Peak Boundary (Q: 0.95 Risk Limit)', color='#FF416C', linestyle='-', linewidth=2.5)

# Fill the high-probability operating reserve zone
plt.fill_between(
    test_stat.index, test_stat['stat_median_pred'], test_stat['stat_peak_pred'],
    color='#FF416C', alpha=0.12, label='Required Grid Spinning Reserve Capacity Zone'
)

# Customizing plot visuals for presentable reports
plt.title("Advanced Predictive Analytics: Multi-Quantile Operational Risk Boundaries", fontsize=14, fontweight='bold', pad=15)
plt.xlabel("Timeline Evaluation Window Vector (UTC)", fontsize=11)
plt.ylabel("Power Magnitudes (Megawatts - MW)", fontsize=11)
plt.grid(True, linestyle='--', alpha=0.3)
plt.legend(fontsize=10.5, facecolor='#FFFFFF', frameon=True, shadow=True, loc='upper left')

plt.gcf().autofmt_xdate()
plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Configure industrial economic cost variables
# Assuming a standard post-crisis baseline market price and a grid deviation penalty fee per MWh
BASE_ELECTRICITY_PRICE_MWH = 65.0  # Average Euro per MWh in Spain
IMBALANCE_PENALTY_PER_MWH = 25.0   # Imbalance fine charged by TSO for scheduling errors

# 2. Build economic ledger dataframe from your advanced evaluation results
econ_df = advanced_eval_df.copy()

# Calculate absolute errors in Megawatts
econ_df['lgb_error_mw'] = np.abs(econ_df[target] - econ_df['lgb_pred'])
econ_df['hybrid_error_mw'] = np.abs(econ_df[target] - econ_df['hybrid_ensemble_pred'])

# 3. Compute continuous financial penalties incurred over time
econ_df['LGBM_Financial_Penalty_EUR'] = econ_df['lgb_error_mw'] * IMBALANCE_PENALTY_PER_MWH
econ_df['Hybrid_Financial_Penalty_EUR'] = econ_df['hybrid_error_mw'] * IMBALANCE_PENALTY_PER_MWH

total_lgbm_loss = econ_df['LGBM_Financial_Penalty_EUR'].sum()
total_hybrid_loss = econ_df['Hybrid_Financial_Penalty_EUR'].sum()
net_savings = total_lgbm_loss - total_hybrid_loss

print("💼 INDUSTRIAL FINANCIAL LOSS AUDIT REPORT")
print("==================================================")
print(f"• Total Penalties Incurred by LightGBM Baseline : €{total_lgbm_loss:,.2f}")
print(f"• Total Penalties Incurred by Hybrid Ensemble   : €{total_hybrid_loss:,.2f}")
print(f"--------------------------------------------------")
print(f"• 💰 TOTAL CAPITAL RECOVERED VIA HYBRID MODEL   : €{net_savings:,.2f}")
print("==================================================")
print(f"🔥 Optimization Metric: Reduced grid penalty liabilities by {((total_lgbm_loss - total_hybrid_loss)/total_lgbm_loss)*100:.1f}%!")

# Create an operational schedule for a flexible industrial facility
econ_df['Optimized_Load_Schedule'] = econ_df['hybrid_ensemble_pred'].copy()

# Identify the highest 3 hours of demand and the lowest 3 hours of demand
peak_hours = econ_df['hybrid_ensemble_pred'].nlargest(3).index
off_peak_hours = econ_df['hybrid_ensemble_pred'].nsmallest(3).index

# Shift 15% of flexible industrial equipment consumption away from peak hours to off-peak slots
flexible_load_pct = 0.15

for ph, oph in zip(peak_hours, off_peak_hours):
    shuffled_load = econ_df.loc[ph, 'hybrid_ensemble_pred'] * flexible_load_pct
    econ_df.loc[ph, 'Optimized_Load_Schedule'] -= shuffled_load
    econ_df.loc[oph, 'Optimized_Load_Schedule'] += shuffled_load

# Calculate total operational energy procurement bills
econ_df['Standard_Bill_EUR'] = econ_df[target] * BASE_ELECTRICITY_PRICE_MWH
econ_df['Optimized_Bill_EUR'] = econ_df['Optimized_Load_Schedule'] * BASE_ELECTRICITY_PRICE_MWH

procure_savings = econ_df['Standard_Bill_EUR'].sum() - econ_df['Optimized_Bill_EUR'].sum()
print(f"⚡ Smart Scheduling Dividend: Shifting flexible capacity saved an additional €{procure_savings:,.2f} in raw utility bills!")

fig, axes = plt.subplots(1, 2, figsize=(18, 6.5))

# Chart A: Cumulative Penalty Loss Trajectory over the timeline
axes[0].plot(econ_df.index, econ_df['LGBM_Financial_Penalty_EUR'].cumsum(), label='Baseline Model Risk Track', color='#FF416C', linewidth=2.5, linestyle='--')
axes[0].plot(econ_df.index, econ_df['Hybrid_Financial_Penalty_EUR'].cumsum(), label='Optimized Hybrid Model Risk Track', color='#8E2DE2', linewidth=3.5)
axes[0].fill_between(econ_df.index, econ_df['LGBM_Financial_Penalty_EUR'].cumsum(), econ_df['Hybrid_Financial_Penalty_EUR'].cumsum(), color='#8E2DE2', alpha=0.15, label='Capital Retained')
axes[0].set_title("Cumulative Grid Risk Penalty Liability Tracking", fontsize=13, fontweight='bold')
axes[0].set_ylabel("Incurred Operational Loss (€)", fontsize=11)
axes[0].legend(loc='upper left', frameon=True, shadow=True)
axes[0].tick_params(axis='x', rotation=15)

# Chart B: Load Profile Shifting Before vs After Optimization
axes[1].plot(econ_df.index, econ_df[target], label='Standard Demand Baseline', color='#111111', linewidth=2, alpha=0.5)
axes[1].plot(econ_df.index, econ_df['Optimized_Load_Schedule'], label='Cost-Optimized Managed Profile', color='#00B4DB', linewidth=3, marker='x')
axes[1].set_title("Demand Response Adjustments: Peak-Load Shifting Strategy", fontsize=13, fontweight='bold')
axes[1].set_ylabel("Electricity Consumption (MW)", fontsize=11)
axes[1].legend(loc='upper left', frameon=True, shadow=True)
axes[1].tick_params(axis='x', rotation=15)

plt.suptitle("Corporate Financial Optimization Hub: Risk Reduction & Utility Cost Mitigation Dashboards", fontsize=15, fontweight='bold', y=0.98)
plt.tight_layout()
plt.show()

# This creates your folder structure automatically
!mkdir -p spain_smart_grid_repo/src
!mkdir -p spain_smart_grid_repo/.github/workflows
!mkdir -p spain_smart_grid_repo/notebooks

# Commented out IPython magic to ensure Python compatibility.
# %%writefile spain_smart_grid_repo/src/verify_pipeline.py
# # This script runs a secure configuration test for GitHub Actions
# import numpy as np
# import pandas as pd
# 
# print("✅ Ingestion Core Framework Validation: SUCCESS")
#

# Commented out IPython magic to ensure Python compatibility.
# 1. 🛑 UPDATE THESE THREE LINES WITH YOUR PERSONAL INFO 🛑
GITHUB_TOKEN = "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"
GITHUB_USERNAME = "pratik-dutta"
REPOSITORY_NAME = "spain-smart-grid-forecaster"

# Move the terminal's focus inside your project folder
# %cd /content/spain_smart_grid_repo

# 2. Configure your Git profile credentials inside the Colab server environment
!git config --global user.email "your_email@example.com"
!git config --global user.name "Your Name"

# 3. Initialize Git transaction tracking and commit your code files
!git init
!git add .
!git commit -m "feat: initial release of advanced smart grid forecasting pipeline v1.0.0"
!git branch -M main

# 4. Construct a secure URL string using your token credentials
remote_url = f"https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@://github.com{GITHUB_USERNAME}/{REPOSITORY_NAME}.git"

# 5. Connect to your blank remote repository and push everything securely
!git remote add origin {remote_url}
!git push -u origin main --force

print("\n🎉 SUCCESS! Refresh your GitHub browser tab to see your complete professional project live!")
# Reset directory focus back to default root
# %cd /content